source_name: farmOS
nav:
# The Home page (index.md) is excluded b/c adding it to the nav menu would be redundant.
- Community:
    - Contributing: community/contributing.md
    - Code of Conduct: community/conduct.md
    - Monthly Call: community/monthly-call.md
    - Chat: https://app.element.io/#/room/#farmOS:matrix.org
    - Forum: https://farmOS.discourse.group/
    - Maintainers: community/maintainers.md
    - Supporters: community/supporters.md
    - Press: community/press.md
    - Trademark: community/trademark.md
    - Donate: donate.md
    - Contrib modules: community/modules
