site_name: farmOS.org
site_url: http://farmos.org
repo_url: https://github.com/farmOS/farmOS.org/
edit_uri: edit/7.x-1.x/docs/
google_analytics: ['UA-56974603-1', 'farmos.org']
nav:
- Home: index.md
- Community:
    - Monthly Call: community/monthly-call.md
    - Chat: https://riot.im/app/#/room/#farmOS:matrix.org
    - Forum: https://farmOS.discourse.group/
    - Farms: community/farms.md
    - Maintainers: community/maintainers.md
    - Supporters: community/supporters.md
    - Press: community/press.md
    - Trademark: community/trademark.md
- Donate: donate.md
